### PR TITLE
Update ccache on Windows to 4.6.1

### PR DESCRIPTION
**Pull request by orgads**
Improved support for MSVC.

### CODE REVIEW

**Comment by orgads** [comment]
Can you please create a new release?

**Comment by jonashaag** [comment]
You can also use a branch or commit ID as version. No need for a new release to use this.

**Comment by hendrikmuhs** [comment]
I plan to create a new release once I figured out the test failures, it seems that `SCCACHE_CACHE_SIZE` support broke with the update.

**Comment by orgads** [comment]
Thank you.

**Pull request merged**
