### PR TITLE
Move cache out of the worktree

### PR DESCRIPTION
**Pull request by krlmlr**
For #96.

### CODE REVIEW

**Comment by krlmlr** [comment]
This action in action: https://github.com/tidyverse/blob/actions/runs/6445932389/job/17500507262#step:6:3405 .

Any idea why sccache fails?

**Comment by hendrikmuhs** [comment]
Did you look at the test? Maybe you have to adapt he location at this line:

https://github.com/hendrikmuhs/ccache-action/blob/main/.github/workflows/tests.yml#L59

**Comment by krlmlr** [comment]
Looks slightly better now, two tests are still failing. Do you agree that moving the cache out of tree is a good idea?

**Comment by hendrikmuhs** [comment]
> Looks slightly better now, two tests are still failing. Do you agree that moving the cache out of tree is a good idea?

yes, I think this is a good idea

**Comment by krlmlr** [comment]
Let's see how far we get with the current implementation after #217. I still think the cache shouldn't live inside the worktree, let's discuss when this becomes an issue.

**Pull request closed without merging**
