### PR TITLE
deps(sccache): bump sccache

### PR DESCRIPTION
**Pull request by compnerd**
Update sccache to 0.7.4 which contains a couple of important fixes for Windows.

### CODE REVIEW

**Comment by hendrikmuhs** [comment]
@compnerd 

Thanks for the change, the other sha is still failing. Can you fix this one as well?

**Comment by compnerd** [comment]
@hendrikmuhs oh, whoops, sorry about that!

**Comment by timangus** [comment]
This fixed ccache-action/sccache for me, for what it's worth. It mysteriously stopped working over the new year period (e.g. https://github.com/graphia-app/graphia/actions/runs/7434050480/job/20227773915). Bit odd though in that it had been working fine with 0.5.3 for at least of couple of months prior to that. Anyway, HEAD working for me now, 1.2.11 not so much.

**Comment by hendrikmuhs** [comment]
Thanks for the feedback!

I can make a release soonish. 

(Unfortunately I am flying blind when it comes to windows and sscache. I don't know if it works or not as I am using neither of the 2 in my projects. So best effort I release something and users use dependabot and if a certain version breaks, they roll back.)

**Comment by compnerd** [comment]
Good to know!  I'm using this for building the swift toolchain, and will hopefully be looking to do more with it soon :).

**Pull request merged**
