### PR TITLE
Add option to add stats to Job Summary page

### PR DESCRIPTION
**Pull request by planetmarshall**
Adds a `job-summary` option that adds the stats to the [Job Summary](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#adding-a-job-summary) section of a workflow run. Requires CCache 4.10+

Also added some unit tests and a workflow job for same.

Just added cache hits for now but is easily extendable. - looks like this:

Screenshot From 2024-11-22 18-55-13

### CODE REVIEW

**Comment by hendrikmuhs** [comment]
Nice!

Do you see a reason why somebody would decide against this? I understand the need for the version check. Given that the version supports it, I would enable it. Or do I miss anything? Is there a usecase for disabling the output?

**Comment by planetmarshall** [comment]
> Nice!
> 
> Do you see a reason why somebody would decide against this? 

No problem. Just being conservative - I'll update the PR enabling the feature by default.

**Comment by TrentHouliston** [comment]
I've done something similar for a private repo, Something that I found looks really good is to use a mermaid diagram to show the direct/preprocessed/missed stats in a pie chart diagram.

https://mermaid.js.org/syntax/pie.html

Since the summaries support github flavoured markdown they render right in the summary view!

e.g.
```mermaid
pie showData title CCache Summary
    "Direct Hits" : 149818
    "Preprocessed Hits" : 1840
    "Misses" : 3743
```

**Comment by hendrikmuhs** [comment]
@planetmarshall Thanks again for the contribution. I think this ready to be merged, however I meanwhile merged some dependabot PRs and caused a merge conflict.

Shall I fix it myself or can you?
I also wonder, do you want to lock into the suggestion from @TrentHouliston? Or is that something for a follow up? - I definitely like the idea and support it, however it could be done in a separate change.

**Comment by planetmarshall** [comment]
> @planetmarshall Thanks again for the contribution. I think this ready to be merged, however I meanwhile merged some dependabot PRs and caused a merge conflict.
> 
> Shall I fix it myself or can you? 

I've updated the branch.

> I also wonder, do you want to lock into the suggestion from @TrentHouliston? Or is that something for a follow up? - I definitely like the idea and support it, however it could be done in a separate change.

I like the the idea but I think it's better added as a future enhancement.

**Pull request merged**
